steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d', '--build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'eclipse-mosquitto:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
