steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d', '-e MOSQUITTO_PASSWORD=${_MOSQUITTO_PASSWORD} MOSQUITTO_USERNAME=${_MOSQUITTO_USERNAME}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
